name: Build and Publish

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: greeting-service

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the source code
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up JDK
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Build & test with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build

      # 4️⃣ Upload JAR as workflow artifact
      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: greeting-service-jar
          path: build/libs/*.jar

      # 5️⃣ Log in to GitHub Container Registry (GHCR)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Build and push Docker image
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
